server:
  port: 8080
  
logging:
  level:
    debug
    
spring:
  rabbitmq: 
    addresses: 192.168.58.144:5672
    username: admin
    password: nmamtf  
    publisherConfirms: true
    queueName: testQueue
    keys:
      orderRouting: order
      orderBounding: order
    exchange: testExchange
    