server:
  port: 8080
  
logging:
  level:
    debug
    
spring:
  rabbitmq: 
    addresses: 192.168.58.145:5672
    username: admin
    password: nmamtf  
    publisherConfirms: true
    queueName: orderQueue
    keys:
      orderRouting: wlf.bussiness.order.*
    exchange: orderExchange
    